### ISSUE TITLE
Subsequent notifications

### ISSUE THREAD

**Issue by tonyshkurenko** [hoodie/notify-rust#95] opened 2021-01-28 16:08 UTC
I need to show multiple subsequent notifications with different timeouts, for example:

1) notification 10s timeout, urgency normal
2) notification 60s timeout, urgency critical
3) notification 10s timeout, urgency normal

I've found, if I use `update()` method, it only updates texts, etc, but doesn't update urgency and timeout, if I use close-show, like:
1) close prev notification, if available
2) show next one, save it

It closes notifications randomly, sometimes without even showing next one

**Comment by hoodie** [comment] 2021-02-02 14:12
I believe this behavior may depend strongly on which desktop environment you may be using.

**Comment by tonyshkurenko** [comment] 2021-02-03 22:20
Ubuntu 20.04, default configuration, if it helps

**Comment by hoodie** [comment] 2021-02-06 11:55
Disclaimer: This library does non of the rendering or internal logic of the actual popup in your desktop environment. It merely makes a well defined api call to a standardized dbus api.

I've checked that in the scenario you described notify-rust sends the proper values. As I said, it is up to the implementation in each desktop environment to interpret these. In ubuntu (gnome) and KDE `critical` notifications do not expire (as is recommended by the spec).
In gnome this even seems to be the case after the urgency lowered again.

As for the timeout, I assume that your observations are due to the fact that the critical notification is persistent.
I can not see not how the this library could/should behave differently. 

Finally the "randomly closing notifications" behavior you describe I cannot quite preproduce, and I would appreciate a reproducer, however, as for the previous issues, I can't make any promises that notify-rust can do anything better there.

**Comment by tonyshkurenko** [comment] 2021-02-06 19:20
Wow, couldn't even expect this level of attention. Yeah, it explains a lot. Thanks!

This is surprise, though :(
> critical notifications do not expire (as is recommended by the spec).

**Closed** 2021-02-06 23:32 UTC
