### ISSUE TITLE
Notifications randomly don't appear on Windows

### ISSUE THREAD

**Issue by MCluck90** [hoodie/notify-rust#79] opened 2020-07-02 21:10 UTC
Most of the time notifications get sent out but occasionally they don't. There doesn't seem to be any relation with how quickly they're sent out. I've tested seconds apart and as much as 20 minutes apart. No errors are reported.

## MCVE

```toml
# Cargo.toml
[package]
name = "pomo"
version = "0.1.0"
edition = "2018"

[dependencies]
notify-rust = "4.0.0"
```

```rust
// src/main.rs
use notify_rust::{Notification, Timeout};

fn main() {
    Notification::new()
        .appname("Pomo")
        .summary("Break time!")
        .timeout(Timeout::Milliseconds(6000))
        .show()
        .unwrap();
}
```

* **OS**: Windows 10
* **rustc**: 1.44.1

**Comment by hoodie** [comment] 2020-07-02 22:24
Hi there, thanks for reporting this. This crate only actually implements notifications for linux by itself. The integration for windows is mostly there for compatibility sake and the heavy lifting for windows is being done by [winrt-notifications](https://docs.rs/winrt-notification/).
We do interpret the `Timeout`, but we only really [cast](https://github.com/hoodie/notify-rust/blob/master/src/notification.rs#L365) it to either `Long` or `Short.
@lucasfernog do you perhaps have an idea as to what might be the problem here?

But I think it might be more enlightening if you could reproduce this behavior with winrt-notifications directly.

**Comment by x4m3** [comment] 2020-07-04 17:55
I also have the same issue, except that notifications would appear 6 hours later 😅

**Comment by lucasfernog** [comment] 2020-07-09 00:14
I've seen this issue when the "do not disturb" mode is enabled (can't remember the name, I don't use windows often).

**Comment by MCluck90** [comment] 2020-07-13 15:40
It would make sense for the "do not disturb" mode. In my case, I've disabled that mode and it still happens 😢

**Comment by hoodie** [comment] 2020-07-13 15:57
hi @MCluck90,
since windows is a second tier target of this library and I can't debug this myself, could you help me by verifying if it could have any other reason? a brief search got me this: https://appuals.com/how-to-fix-notifications-on-windows-10/
could it be a windows bug?
have you brought this up as a possible issue of https://github.com/allenbenz/winrt-notification?

thank you

**Comment by MCluck90** [comment] 2020-07-13 15:59
Yeah, no worries. I'll dig in to it and see if I can come up with a solution

**Comment by deepy** [comment] 2020-12-18 09:17
I've been unable to get any notifications to work on windows, winrt-notifications has a single open issue which may or may not be related.

**Comment by hoodie** [comment] 2021-01-08 22:44
closing this since this is more an issue for winrt-notifications AFAIK

**Closed by hoodie** 2021-01-08 22:44 UTC

**Comment by allenbenz** [comment] 2021-02-16 10:26
[0.2.3](https://crates.io/crates/winrt-notification/0.2.3) resolves toasts randomly not showing up. Don't take 0.3.0, has an issue where it doesn't build with the gnu target.

**Comment by hoodie** [comment] 2021-02-16 22:17
woop \0/
